// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGNezdppdFeQocjukIXPyFV8q3ZNhsjKo',
    appId: '1:542924632835:web:6d8c5a6288d3d456a66f36',
    messagingSenderId: '542924632835',
    projectId: 'clothing-b6e79',
    authDomain: 'clothing-b6e79.firebaseapp.com',
    storageBucket: 'clothing-b6e79.firebasestorage.app',
    measurementId: 'G-VVSX7ENDZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLzYcBqzlicGCmk-uxyVnswFWqGc41rI',
    appId: '1:542924632835:android:0c0ba333b2e64ed7a66f36',
    messagingSenderId: '542924632835',
    projectId: 'clothing-b6e79',
    storageBucket: 'clothing-b6e79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtEjk5BlwxW-pUbCJRavQxhq6XXJVtR8',
    appId: '1:542924632835:ios:b524209f7e6fddbea66f36',
    messagingSenderId: '542924632835',
    projectId: 'clothing-b6e79',
    storageBucket: 'clothing-b6e79.firebasestorage.app',
    iosClientId: '542924632835-jf8ik872oe293s9ci1cf1pto81un0gd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtEjk5BlwxW-pUbCJRavQxhq6XXJVtR8',
    appId: '1:542924632835:ios:b524209f7e6fddbea66f36',
    messagingSenderId: '542924632835',
    projectId: 'clothing-b6e79',
    storageBucket: 'clothing-b6e79.firebasestorage.app',
    iosClientId: '542924632835-jf8ik872oe293s9ci1cf1pto81un0gd8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGNezdppdFeQocjukIXPyFV8q3ZNhsjKo',
    appId: '1:542924632835:web:6e92121c3008d5d1a66f36',
    messagingSenderId: '542924632835',
    projectId: 'clothing-b6e79',
    authDomain: 'clothing-b6e79.firebaseapp.com',
    storageBucket: 'clothing-b6e79.firebasestorage.app',
    measurementId: 'G-KRQ0K9T14Z',
  );

}